### ISSUE TITLE
Can't start courier

### ISSUE THREAD

**Issue by Walkyst** [Dragovorn/courier#16]
I get this error when starting courier with this command `java -jar Courier.jar`
Builded this .jar with `mvn package`
Maybe i do something wrong, because only work with gradle
Java: 8u51 (64-bit)
OC: Windows 10 LTSC (64-bit)

```
Exception in thread "main" java.lang.NoClassDefFoundError: dorkbox/systemTray/Entry
        at com.dragovorn.courier.Main.main(Main.java:32)
Caused by: java.lang.ClassNotFoundException: dorkbox.systemTray.Entry
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 1 more
```

**Comment by Dragovorn** [comment]
Try running `mvn clean package shade:shade`, that should shade the
dependencies properly.

**Comment by Walkyst** [comment]
Thanks, it work now
